[project]
name = "log-scrubber"
version = "0.9.5"
description = "Scrub logs of sensitive data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
scrubber = "scrubber.main:main"